### ISSUE TITLE
isAccessTokenValid() is always false

### ISSUE THREAD

**Issue by kyleabens** [intuit/oauth-jsclient#22]
I’m confused as to how isAccessTokenValid() works.  I currently save the access_token to my user in my database when they first connect their quickbooks account.  So how would any subsequent api calls know what the access token is and if it’s valid?  Should I be passing the access token explicitly somewhere to see if it’s valid?  Thanks for the help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by abisalehalliprasan** [comment]
@kyleabens : 
Before making any API calls, just call the helper method `isAccessTokenValid()` as shown below : 
https://github.com/intuit/oauth-jsclient#is-accesstoken-valid

This issue #21 was fixed with PR #20. Please use the latest version of the package ~ [1.2.0](https://github.com/intuit/oauth-jsclient/tree/1.2.0)

Since this library is not a fully blown SDK, you might need to call the above helper method explicitly every time you are making an API call in your app.

**Comment by kyleabens** [comment]
@abisalehalliprasan should I set the token first `oauthClient.setToken(token);`?  How would isAccessTokenValid() know what the token is in the first place and if it's valid or not?

**Comment by abisalehalliprasan** [comment]
@kyleabens : 

If you are using this client to Authenticate? 
for ex: as shown [here](https://github.com/intuit/oauth-jsclient#step-2) , then you need not worry about setting the tokens. The OAuth Client does it for you.

However, if you are setting the tokens explicitly just refer to :
[Set Tokens](https://github.com/intuit/oauth-jsclient#set-the-token-) 

So for your app, you could have this process : 
`setToken(authToken) -> isAccessTokenValid() -> MakeAPICall()`

**Note:** The `authToken` should be generated using this client.

**Comment by kyleabens** [comment]
@abisalehalliprasan Okay thanks.  I figured out that my problem was not passing a createdAt timestamp with my token so the token was always valid.  Once I added that then it started working and refreshing when needed.
